# Generated by Django 4.2.7 on 2025-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_activity_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_payout_at",
            field=models.DateTimeField(
                blank=True, help_text="Last payout date", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="payout_status",
            field=models.CharField(
                choices=[
                    ("eligible", "Eligible"),
                    ("pending_verification", "Pending Verification"),
                    ("suspended", "Suspended"),
                ],
                default="pending_verification",
                help_text="Payout eligibility status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="paypal_email",
            field=models.EmailField(
                blank=True,
                help_text="PayPal email for payouts (if selected)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_payout_method",
            field=models.CharField(
                choices=[("stripe_bank", "Stripe Bank Transfer"), ("paypal", "PayPal")],
                default="stripe_bank",
                help_text="Preferred payout method",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stripe_connect_account_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Connect account for payouts",
                max_length=128,
                null=True,
            ),
        ),
    ]
