# Generated by Django 4.2.7 on 2025-07-31 15:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payoutrequest_payoutrequest_positive_payout_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Code becomes active when promotion starts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='30 days from creation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_organization',
            field=models.BooleanField(default=False, help_text='Whether this user represents an organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_payout_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum payout amount for organizations', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Display name for the organization', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_type',
            field=models.CharField(blank=True, help_text='Type of organization (501c3, church, school, etc.)', max_length=50),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='When the promotion goes live')),
                ('code_entry_deadline', models.DateTimeField(help_text='30 days after start (last day to enter codes)')),
                ('end_date', models.DateTimeField(help_text='60 days after start (last day for purchases)')),
                ('is_active', models.BooleanField(default=False)),
                ('total_allocations', models.IntegerField(default=0, help_text='Number of users who have this code')),
                ('organization', models.ForeignKey(limit_choices_to={'profile__is_organization': True}, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.referralcode')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('data_verified', 'Data Verified'), ('manually_verified', 'Manually Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tax_id_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('website_verified', models.BooleanField(default=False)),
                ('manual_verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100)),
                ('contact_person_role', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(limit_choices_to={'profile__is_organization': True}, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_form_type', models.CharField(blank=True, max_length=20)),
                ('tax_exempt_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(limit_choices_to={'profile__is_organization': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tax_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Tax Information',
                'verbose_name_plural': 'Organization Tax Information',
            },
        ),
        migrations.CreateModel(
            name='UserReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.DecimalField(decimal_places=2, help_text="Percentage of user's earnings allocated to this code", max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.referralcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_userr_user_id_3c788f_idx'), models.Index(fields=['referral_code', 'is_active'], name='users_userr_referra_6e0894_idx')],
                'unique_together': {('user', 'referral_code')},
            },
        ),
        migrations.CreateModel(
            name='ReferralDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_disbursements', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.referralcode')),
                ('wallet_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_disbursements', to='users.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_user', 'status'], name='users_refer_recipie_db309b_idx'), models.Index(fields=['referral_code', 'status'], name='users_refer_referra_6a66c8_idx'), models.Index(fields=['wallet_transaction'], name='users_refer_wallet__1285f3_idx'), models.Index(fields=['created_at'], name='users_refer_created_0e0fa7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='users_refer_code_f1218a_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['owner', 'is_active'], name='users_refer_owner_i_10cbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['expires_at'], name='users_refer_expires_be344f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['organization', 'is_active'], name='users_promo_organiz_3daedb_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='users_promo_start_d_b7dbde_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code_entry_deadline'], name='users_promo_code_en_25ade3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationverification',
            index=models.Index(fields=['verification_status'], name='users_organ_verific_36a06a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationverification',
            index=models.Index(fields=['organization'], name='users_organ_organiz_4c3927_idx'),
        ),
    ]
