# Generated by Django 4.2.7 on 2025-07-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_referralcode_userprofile_is_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code_entry_deadline',
            field=models.DateTimeField(blank=True, help_text='30 days after start (auto-calculated if blank)', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='60 days after start (auto-calculated if blank)', null=True),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='30 days from creation (auto-set if blank)', null=True),
        ),
    ]
