# Generated by Django 4.2.7 on 2025-05-01 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
