# Generated by Django 4.2.7 on 2025-05-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliatelink",
            name="affiliate_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="affiliatelink",
            name="original_url",
            field=models.TextField(),
        ),
    ]
