# Generated by Django 4.2.7 on 2025-06-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_remove_offer_unique_product_vendor_offer_and_more"),
        ("affiliates", "0003_productassociation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatelink",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Commission percentage (duplicated to Offer for convenience)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="affiliatelink",
            name="error_count",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive errors when checking URL"
            ),
        ),
        migrations.AddField(
            model_name="affiliatelink",
            name="is_url_valid",
            field=models.BooleanField(
                default=True, help_text="Whether the affiliate URL is currently working"
            ),
        ),
        migrations.AddField(
            model_name="affiliatelink",
            name="last_checked",
            field=models.DateTimeField(
                blank=True, help_text="When affiliate URL was last validated", null=True
            ),
        ),
        migrations.AddField(
            model_name="affiliatelink",
            name="offer",
            field=models.OneToOneField(
                blank=True,
                help_text="Connected offer in unified pricing system (for hybrid approach)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliate_link",
                to="offers.offer",
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatelink",
            index=models.Index(
                fields=["platform"], name="affiliates__platfor_d46e49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatelink",
            index=models.Index(
                fields=["is_active", "is_url_valid"],
                name="affiliates__is_acti_aa85e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatelink",
            index=models.Index(
                fields=["last_checked"], name="affiliates__last_ch_758aa9_idx"
            ),
        ),
    ]
