# Generated by Django 4.2.7 on 2025-06-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0004_affiliatelink_commission_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatelink",
            name="is_processing",
            field=models.BooleanField(
                default=False,
                help_text="Whether affiliate URL generation is currently in progress",
            ),
        ),
        migrations.AddField(
            model_name="affiliatelink",
            name="processing_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When affiliate URL generation started", null=True
            ),
        ),
    ]
