# Generated by Django 4.2.7 on 2025-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
