# Generated by Django 4.2.7 on 2025-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offer_is_active"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offer",
            name="unique_product_vendor_offer",
        ),
        migrations.AddField(
            model_name="offer",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Commission percentage for affiliate offers (e.g., 5.00 for 5%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="expected_commission",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated expected commission amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("supplier", "Direct Supplier"),
                    ("affiliate", "Affiliate Referral"),
                ],
                default="supplier",
                help_text="Whether this is a direct supplier offer or affiliate referral",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="price_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Historical price data for tracking price changes",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="price_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="When price was last fetched from affiliate platform",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["offer_type"], name="offers_offe_offer_t_305478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["selling_price"], name="offers_offe_selling_47189a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["is_active", "is_in_stock"],
                name="offers_offe_is_acti_582dac_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                fields=("product", "vendor", "offer_type"),
                name="unique_product_vendor_offer_type",
            ),
        ),
    ]
