# Generated by Django 4.2.7 on 2025-08-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
        ("offers", "0003_remove_offer_unique_product_vendor_offer_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offer",
            name="unique_product_vendor_offer_type",
        ),
        migrations.AddField(
            model_name="offer",
            name="is_confirmed",
            field=models.BooleanField(
                default=True,
                help_text="Whether this price is confirmed/guaranteed (False for quote-based estimates)",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="source_quote",
            field=models.ForeignKey(
                blank=True,
                help_text="Source quote if this offer was generated from quote analysis",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_offers",
                to="quotes.quote",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("supplier", "Direct Supplier"),
                    ("affiliate", "Affiliate Referral"),
                    ("quote", "Quote-Based Pricing"),
                ],
                default="supplier",
                help_text="Whether this is a direct supplier offer or affiliate referral",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                fields=("product", "vendor", "offer_type", "source_quote"),
                name="unique_product_vendor_offer_quote",
            ),
        ),
    ]
