# Generated by Django 4.2.7 on 2025-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="affiliate_program",
            field=models.CharField(
                blank=True, help_text="Name of affiliate program", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="default_commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default commission rate for this affiliate vendor",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_affiliate",
            field=models.BooleanField(
                default=False, help_text="Whether this is an affiliate marketplace"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of name",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(
                choices=[
                    ("supplier", "Direct Supplier"),
                    ("affiliate", "Affiliate Marketplace"),
                    ("distributor", "Distributor"),
                ],
                default="supplier",
                help_text="Type of vendor relationship",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="website",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["vendor_type"], name="vendors_ven_vendor__c9b79e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_affiliate"], name="vendors_ven_is_affi_56c9f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_active"], name="vendors_ven_is_acti_5c8a37_idx"
            ),
        ),
    ]
