# Generated by Django 4.2.7 on 2025-06-10 16:08

from django.db import migrations
from django.utils.text import slugify


def populate_vendor_slugs(apps, schema_editor):
    """Populate slug fields for existing vendors"""
    Vendor = apps.get_model('vendors', 'Vendor')
    
    for vendor in Vendor.objects.filter(slug__isnull=True):
        base_slug = slugify(vendor.name)
        slug = base_slug
        counter = 1
        
        # Handle duplicate slugs
        while Vendor.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        vendor.slug = slug
        vendor.save(update_fields=['slug'])


def reverse_populate_vendor_slugs(apps, schema_editor):
    """Reverse migration - clear slug fields"""
    Vendor = apps.get_model('vendors', 'Vendor')
    Vendor.objects.update(slug=None)


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_vendor_affiliate_program_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_vendor_slugs,
            reverse_populate_vendor_slugs,
        ),
    ]
