# Generated by Django 4.2.7 on 2025-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="pdf_content",
            field=models.BinaryField(
                blank=True, help_text="Raw PDF content for Heroku processing", null=True
            ),
        ),
    ]
