# Generated by Django 4.2.7 on 2025-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="source",
            field=models.CharField(
                choices=[
                    ("amazon", "Amazon"),
                    ("web_scrape", "Web Scrape"),
                    ("partner_import", "Partner Import"),
                    ("manual", "Manual Entry"),
                    ("user_contributed", "User Contributed"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
