# Generated by Django 4.2.7 on 2025-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Mark this product as demo data for testing/presentations",
            ),
        ),
    ]
