# Generated by Django 4.2.7 on 2025-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_is_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="future_demand_count",
            field=models.IntegerField(
                default=0, help_text="Number of times this product was searched for"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="last_demand_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time someone searched for this product",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="source",
            field=models.CharField(
                choices=[
                    ("amazon", "Amazon"),
                    ("web_scrape", "Web Scrape"),
                    ("partner_import", "Partner Import"),
                    ("manual", "Manual Entry"),
                    ("user_contributed", "User Contributed"),
                    ("future_demand", "Future Demand Tracking"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("discontinued", "Discontinued"),
                    ("pending", "Pending"),
                    ("future_opportunity", "Future Opportunity"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
