# Generated by Django 4.2.7 on 2025-06-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0004_product_future_demand_count_product_last_demand_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_placeholder",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
